# -*- coding: utf-8 -*-
"""load_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13MTW-FR0fxHf9oTu0g2xhvSwQCopcMWW
"""

import json
import os
import torch
from torch.utils.data import DataLoader
from .dataset import SFTDataset

def get_loaders(args):
    # Το path που θα δημιουργήσουμε στο Colab
    path = 'data/natural_instructions.jsonl'

    if not os.path.exists(path):
        raise FileNotFoundError(f"Το αρχείο δεδομένων δεν βρέθηκε στο {path}. Βεβαιωθείτε ότι έτρεξε το data preparation στο Colab.")

    with open(path, 'r') as f:
        data = [json.loads(line) for line in f]

    # Διαχωρισμός 90% εκπαίδευση, 10% αξιολόγηση
    split = int(len(data) * 0.9)
    train_data = data[:split]
    eval_data = data[split:]

    train_dataset = SFTDataset(train_data, args.model)
    eval_dataset = SFTDataset(eval_data, args.model)

    # Μοίρασμα των δεδομένων στους clients (Federated Learning)
    num_clients = args.num_clients
    client_data_size = len(train_dataset) // num_clients
    train_loaders = []

    for i in range(num_clients):
        start_idx = i * client_data_size
        end_idx = (i + 1) * client_data_size
        indices = list(range(start_idx, end_idx))
        subset = torch.utils.data.Subset(train_dataset, indices)
        train_loaders.append(DataLoader(subset, batch_size=1, shuffle=True))

    eval_loader = DataLoader(eval_dataset, batch_size=1, shuffle=False)

    return train_loaders, eval_loader, None

def get_loaders_for_filtering(args):
    # Απαραίτητο για να μην χτυπάει το import στο main.py
    return None, None, None